### ISSUE TITLE
[Feature]: API Client can Create `bits` Packages via `POST /v3/packages`

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry/cf-k8s-api#37]
### Blockers/Dependencies

* Blocked on the final structure of the `CFPackage` resource https://github.com/cloudfoundry/cf-crd-explorations/issues/76

### Background

Description of Packages from the [API Docs](https://v3-apidocs.cloudfoundry.org/version/3.104.0/index.html#packages):
> #### Packages
> A package is an application’s ‘source code’; either raw bits for your application or a pointer to these bits.
> In Cloud Foundry, packages are staged to produce an executable Droplet. We currently support raw bits and Docker packages.

This story will be introducing the `POST /v3/packages` endpoint to the API Shim for creating `bits` type packages. At this time we are not planning on supporting `docker` type packages in the shim.

**As a** Developer
**I want to** be able to create `bits` type Packages
**So that** I can upload the source code for my App for staging

### Happy Path
**GIVEN** I have the [cf-k8s-controllers](https://github.com/cloudfoundry/cf-k8s-controllers) installed and the API shim is running
**AND**
**GIVEN** I have a `CFApp` CR applied
**WHEN** I make the following request
```
curl "https://api.example.org/v3/packages" \
  -X POST \
  -H "Authorization: bearer <some-placeholder-token>" \
  -H "Content-type: application/json" \
  -d '{
    "type": "bits",
    "relationships": {
      "app": {
        "data": {
          "guid": "[guid-for-my-app]"
        }
      }
    }
  }'
```
**THEN** I can see a `CFPackage` CR created in the same namespace as the related App and get back the following response

```json
{
  "guid": "44f7c078-0934-470f-9883-4fcddc5b8f13",
  "type": "bits",
  "data": {},
  "state": "AWAITING_UPLOAD",
  "created_at": "2015-11-13T17:02:56Z",
  "updated_at": "2016-06-08T16:41:26Z",
  "relationships": {
    "app": {
      "data": {
        "guid": "1d3bf0ec-5806-43c4-b64e-8364dba1086a"
      }
    }
  },
  "links": {
    "self": {
      "href": "https://api.example.org/v3/packages/44f7c078-0934-470f-9883-4fcddc5b8f13"
    },
    "upload": {
      "href": "https://api.example.org/v3/packages/44f7c078-0934-470f-9883-4fcddc5b8f13/upload",
      "method": "POST"
    },
    "download": {
      "href": "https://api.example.org/v3/packages/44f7c078-0934-470f-9883-4fcddc5b8f13/download",
      "method": "GET"
    },
    "app": {
      "href": "https://api.example.org/v3/apps/1d3bf0ec-5806-43c4-b64e-8364dba1086a"
    }
  },
  "metadata": {
    "labels": { },
    "annotations": { }
  }
}
```

---

### App does not exist
**GIVEN** I have the [cf-k8s-controllers](https://github.com/cloudfoundry/cf-k8s-controllers) installed and the API shim is running
**WHEN** I make the following request
```
curl "https://api.example.org/v3/packages" \
  -X POST \
  -H "Authorization: bearer <some-placeholder-token>" \
  -H "Content-type: application/json" \
  -d '{
    "type": "bits",
    "relationships": {
      "app": {
        "data": {
          "guid": "[guid-for-app-that-doesn't-exist]"
        }
      }
    }
  }'
```
**THEN** I see that a `CFPackage` resource was **not created** and I get back the following response
```
HTTP/1.1 422 Unprocessable Entity

{
  "errors": [
    {
      "detail": "App is invalid. Ensure it exists and you have access to it.",
      "title": "CF-UnprocessableEntity",
      "code": 10008
    }
  ]
}
```

---

### Invalid type
**GIVEN** I have the [cf-k8s-controllers](https://github.com/cloudfoundry/cf-k8s-controllers) installed and the API shim is running
**WHEN** I make the following request
```
curl "https://api.example.org/v3/packages" \
  -X POST \
  -H "Authorization: bearer <some-placeholder-token>" \
  -H "Content-type: application/json" \
  -d '{
    "type": "docker",
    "relationships": {
      "app": {
        "data": {
          "guid": "[guid-for-app-that-doesn't-exist]"
        }
      }
    }
  }'
```
**THEN** I see that a `CFPackage` resource was **not created** and I get back the following response
```
HTTP/1.1 422 Unprocessable Entity

{
  "errors": [
    {
      "detail": "Type must be 'bits'. Docker Packages are not supported.",
      "title": "CF-UnprocessableEntity",
      "code": 10008
    }
  ]
}
```

---

### Missing relationships
**GIVEN** I have the [cf-k8s-controllers](https://github.com/cloudfoundry/cf-k8s-controllers) installed and the API shim is running
**WHEN** I make the following request
```
curl "https://api.example.org/v3/packages" \
  -X POST \
  -H "Authorization: bearer <some-placeholder-token>" \
  -H "Content-type: application/json" \
  -d '{
    "type": "bits"
  }'
```
**THEN** I see that a `CFPackage` resource was **not created** and I get back the following response
```
HTTP/1.1 422 Unprocessable Entity

{
  "errors": [
    {
      "detail": "Relationships 'relationships' is not an object.",
      "title": "CF-UnprocessableEntity",
      "code": 10008
    }
  ]
}
```

---

### Bad relationship
**PRODUCT QUESTION:** There's a whole lot to unpack here. Lots of error messages that Cloud Controller can spit out.
A lot of the [errors are metaprogrammed](https://github.com/cloudfoundry/cloud_controller_ng/blob/d40dbbe0c666c5cc53e32b626b166316504118e8/app/messages/validators.rb#L203), too, so they're hard to enumerate. If it's too much work I feel we could just fall back on either "`Relationships App must be an object`" or "`Relationships App must be structured like this: \"app: {\"data\": {\"guid\": \"valid-guid\"}}\"`" for all of the cases. The most important thing here is the `422 Unprocessable Entity` / `10008` code response. This is an opportunity to sync up with the product folks on the team.

**GIVEN** I have the [cf-k8s-controllers](https://github.com/cloudfoundry/cf-k8s-controllers) installed and the API shim is running
**WHEN** I make the following request
```
curl "https://api.example.org/v3/packages" \
  -X POST \
  -H "Authorization: bearer <some-placeholder-token>" \
  -H "Content-type: application/json" \
  -d '{
    "type": "bits",
    "relationships": {
      "build": {
        "data": {

        }
      }
    }
  }'
```
**THEN** I see that a `CFPackage` resource was **not created** and I get back the following response
```
HTTP/1.1 422 Unprocessable Entity

{
  "errors": [
    {
      "detail": "Relationships Unknown field(s): 'build', Relationships App can't be blank, Relationships App must be structured like this: \"app: {\"data\": {\"guid\": \"valid-guid\"}}\"",
      "title": "CF-UnprocessableEntity",
      "code": 10008
    }
  ]
}
```

---

### Documentation

Document this endpoint in our [api docs](https://github.com/cloudfoundry/cf-k8s-api/blob/main/docs/api.md) and note that `docker` type Packages are not supported.

### Dev Notes

* Relevant [Cloud Controller code](https://github.com/cloudfoundry/cloud_controller_ng/blob/d40dbbe0c666c5cc53e32b626b166316504118e8/app/controllers/v3/packages_controller.rb#L145) for creating a new Package

**Comment by matt-royal** [comment]
Note: the status should be 201 in the success case, not 200.

**Comment by matt-royal** [comment]
WIP is on the branch `issues/37`

**Comment by matt-royal** [comment]
### Tasks
- [ ] Wire the handler into the main
- [ ] Wire the handler into routing
- [ ] Implement the Package repository
- [ ] Implement the handler happy path
- [ ] Implement the handler sad paths
