### ISSUE TITLE
[Feature]: API Client can create a Build via `POST /v3/builds` without optional fields

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry/cf-k8s-api#52]
### Blockers/Dependencies

This should not be worked on at the same time as #53 , but the order in which they are worked does not matter.

### Background

**As a** client of the CF API
**I want** to be able to create Builds
**So that** I can stage my App

### Happy Path
**GIVEN** I have the shim running and cf-k8s-controllers installed and deployed to my K8s cluster
**AND** I have a ready Package CR applied
**WHEN** I make the following request

```bash
curl "https://api-shim.example.org/v3/builds" \
  -X POST \
  -H "Authorization: bearer <placeholder-bearer-token>" \
  -H "Content-type: application/json" \
  -d '{
    "package": {
       "guid": "<package-guid>"
    }
  }'
```

**THEN** I see a Build CR created in the **same namespace** as the associated Package and its state set to `STAGING`
**AND** I get back the following response:

```json
HTTP/1.1 201 Created
Content-Type: application/json

{
  "guid": "585bc3c1-3743-497d-88b0-403ad6b56d16",
  "created_at": "2016-03-28T23:39:34Z",
  "updated_at": "2016-06-08T16:41:26Z",
  "created_by": {},  # <-------------------- Send an empty object
  "state": "STAGING",
  "staging_memory_in_mb": 1024,
  "staging_disk_in_mb": 1024,
  "error": null,
  "lifecycle": {
    "type": "buildpack",
    "data": {
      "buildpacks": [],
      "stack": "cflinuxfs3"
    }
  },
  "package": {
    "guid": "8e4da443-f255-499c-8b47-b3729b5b7432"
  },
  "droplet": null,
  "relationships": {
    "app": {
      "data": {
        "guid": "7b34f1cf-7e73-428a-bb5a-8a17a8058396"
      }
    }
  },
  "metadata": {
    "labels": { },
    "annotations": { }
  },
  "links": {
    "self": {
      "href": "https://api.example.org/v3/builds/585bc3c1-3743-497d-88b0-403ad6b56d16"
    },
    "app": {
      "href": "https://api.example.org/v3/apps/7b34f1cf-7e73-428a-bb5a-8a17a8058396"
    }
  }
}
```

---

### Sad Path: Package does not exist

**GIVEN** I have the shim running and cf-k8s-controllers installed and deployed to my K8s cluster
**AND** I **do not** have a Package CR applied
**WHEN** I make the following request

```bash
curl "https://api-shim.example.org/v3/builds" \
  -X POST \
  -H "Authorization: bearer <placeholder-bearer-token>" \
  -H "Content-type: application/json" \
  -d '{
    "package": {
       "guid": "<non-existant-package-guid>"
    }
  }'
```

**THEN** No Build CR is created and I get back the following response

```json
HTTP/1.1 422 Unprocessable Entity

{
  "errors": [
    {
      "detail": "Unable to use package. Ensure that the package exists and you have access to it.",
      "title": "CF-UnprocessableEntity",
      "code": 10008
    }
  ]
}
```

---

### Sad Path: Invalid fields

Look at the following code and see if there are any superficial validations that are cheap to add (like asserting that the disk and memory values are positive integers):
* https://github.com/cloudfoundry/cloud_controller_ng/blob/03c7501116f87b660dd2199601cba973ff5c3618/app/controllers/v3/builds_controller.rb#L29
* https://github.com/cloudfoundry/cloud_controller_ng/blob/03c7501116f87b660dd2199601cba973ff5c3618/app/messages/build_create_message.rb#L13-L14

We want to prioritize getting the basic functionality of these endpoints in first and we can layer on additional error handling later.

### Dev Notes

* V3 API Docs: https://v3-apidocs.cloudfoundry.org/version/3.106.0/index.html#create-a-build
* Specifying a custom `lifecycle` is out of scope for this story
* Ignore the `created_by` field for now. It's a seldom-used field in CF for VMs that was only added to Builds and likely doesn't make sense in a world where we're dealing with opaque tokens and don't have a UAA / `users` table in our db.
* Ignore optional request parameters like `lifecycle` and memory/disk requests for now. We can add them in follow-up stories.

**Comment by gnovv** [comment]
### Tasks
- [ ] Implement the handler happy path
  - [ ] Unit Tests
  - [ ] Implement the Build create message
  - [ ] Implement the Build repository
    - [ ] Integration Tests
- [ ] Implement the handler sad paths
  - [ ] Unit Tests
  - [ ] Build Repo Integration Test (returns an error)
- [ ] Wire the handler into the main
- [ ] Update README `api.md`
- [ ] Test with a real cluster
- [ ] Open PR & merge

**Comment by gnovv** [comment]
Validating optional fields is non-trivial, since the issue says to ignore the optional fields anyway we will punt on this.
The only validation is that the input is JSON and the package needs to exist.
