### ISSUE TITLE
[Feature]: API Client can get a Build via GET /v3/builds/<build_guid>

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry/cf-k8s-api#53]
### Blockers/Dependencies

This should not be worked on at the same time as #52, but the order in which they are worked does not matter.

### Background

**As a** client of the API shim
**I want** to be able to view a single Build
**So that** I can see the status of the staging process and know what Droplet was produced

The CF CLI polls this endpoint constantly while an App is staging to know when staging is complete.

### Happy Path
**GIVEN** I have the shim running and cf-k8s-controllers installed and deployed to my K8s cluster
**AND** I have previously created a CFBuild
**WHEN I** make the following request

```bash
curl "https://api-shim.example.org/v3/builds/<build-guid>" \
  -X GET \
  -H "Authorization: bearer <placeholder-bearer-token>"
```

**THEN I** I get back a response with information that matches the Build CR
```json
HTTP/1.1 200 OK
Content-Type: application/json

{
  "guid": "585bc3c1-3743-497d-88b0-403ad6b56d16",
  "created_at": "2016-03-28T23:39:34Z",
  "updated_at": "2016-03-28T23:39:47Z",
  "created_by": {},
  "state": "STAGING",
  "staging_memory_in_mb": 1024, # <----- return whats on the CR
  "staging_disk_in_mb": 1024, # <----- return whats on the CR
  "error": null,
  "lifecycle": {
    "type": "buildpack",
    "data": {
      "buildpacks": [ "ruby_buildpack" ],
      "stack": "cflinuxfs3"
    }
  },
  "package": {
    "guid": "8e4da443-f255-499c-8b47-b3729b5b7432"
  },
  "droplet": null,
  "relationships": {
    "app": {
      "data": {
        "guid": "7b34f1cf-7e73-428a-bb5a-8a17a8058396"
      }
    }
  },
  "metadata": {
    "labels": { },
    "annotations": { }
  },
  "links": {
    "self": {
      "href": "https://api.example.org/v3/builds/585bc3c1-3743-497d-88b0-403ad6b56d16"
    },
    "app": {
      "href": "https://api.example.org/v3/apps/7b34f1cf-7e73-428a-bb5a-8a17a8058396"
    },
    "droplet": {
      "href": "https://api.example.org/v3/droplets/1e1186e7-d803-4c46-b9d6-5c81e50fe55a"
    }
  }
}
```

---

### Sad Path: Build cannot be found
**GIVEN** I have the shim running and cf-k8s-controllers installed and deployed to my K8s cluster
**AND** a Build **does not exist** that matches the guid I request
**WHEN I** make the following request

```bash
curl "https://api-shim.example.org/v3/builds/<fake-non-existant-build-guid>" \
  -X GET \
  -H "Authorization: bearer <placeholder-bearer-token>"
```

**THEN** I get back the following response

```json
HTTP/1.1 404 Not Found

{
  "errors": [
    {
      "detail": "Build not found",
      "title": "CF-ResourceNotFound",
      "code": 10010
    }
  ]
}
```

### Dev Notes

* V3 API Docs: https://v3-apidocs.cloudfoundry.org/version/3.106.0/index.html#get-a-build
* Verify with a CF for VMs environment what an initial Build looks like before staging is complete

**Comment by gnovv** [comment]
### Tasks
- [ ] Implement the handler happy path
- [ ] Implement the handler sad paths
- [ ] Wire the handler into the main
- [ ] Wire the handler into routing
- [ ] Implement the Build presenter
- [ ] Implement the Build repository

**Comment by gnovv** [comment]
We are punting on the error field for now,
Surfacing errors from the build process is complicated and out of scope for this story.
